markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /:year/:month/:title/
url: http://cooller000.github.io
author: Cooller000
pygments: true
paginate: 24
comments: custom
